### ISSUE TITLE
Step 6 error?

### ISSUE THREAD

**Issue by tdowrick** [UCL/scikit-surgerydocker#19]
When I try and run this line from step 6, I get an error, presumably because the team1 tag doesn't exist at this point?

```
docker save my-project:team1 > my-project-team1.tar
```

@mianasbat

**Comment by mianasbat** [comment]
Thanks @tdowrick Yeah I didnt tag the image in updated docs.
I will update it.

**Comment by mianasbat** [comment]
Closing this issue because it is fixed and the whole app is under retest in issue #30
